---
- name: Substituindo Zabbix Agente 1 pelo Agente 2
  hosts: zabbix_agents
  become: yes
  vars:
    zabbix_repo_url: "https://repo.zabbix.com/zabbix/6.4/debian/pool/main/z/zabbix-release/zabbix-release_6.4-1%2Bdebian10_all.deb"
    zabbix_conf_template: "zabbix_agent2.conf.j2"

  tasks:
    - name: Parando agente do Zabbix 1
      service:
        name: zabbix-agent
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: Removendo Zabbix Agent 1
      apt:
       name: zabbix*
       state: absent
      ignore_errors: yes

    - name: Baixando Zabbix Agent 2 repo
      get_url:
        url: "{{ zabbix_repo_url }}"
        dest: "/tmp/zabbix-release.deb"

    - name: Instalando Zabbix Agent 2 repo
      apt:
        deb: "/tmp/zabbix-release.deb"
        state: present

    - name: Atualizando repositórios
      apt:
        update_cache: yes

    - name: Continuando a instalação
      apt:
        name:
          - zabbix-agent2
          - zabbix-agent2-plugin-*
        state: present

    - name: Configurando Zabbix Agent 2
      template:
        src: "{{ zabbix_conf_template }}"
        dest: /etc/zabbix/zabbix_agent2.conf
        owner: root
        group: root
        mode: '0644'

    - name: Habilitando e iniciando Zabbix Agent 2
      service:
        name: zabbix-agent2
        state: started
        enabled: yes

    - name: Reiniciar o serviço zabbix-agent2
      service:
        name: zabbix-agent2
        state: restarted
