---
- name: Instalar e configurar o agente do Wazuh no debian
  hosts: SERVER # Lista de servidores
  become: true  # Torna-se root para executar tarefas

  tasks:
    - name: Baixar o pacote do agente do Wazuh
      get_url:
        url: "https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.7.2-1_amd64.deb"
        dest: "/tmp/wazuh-agent_4.7.2-1_amd64.deb"
        mode: '0755'

    - name: Instalar o pacote do agente do Wazuh
      shell: dpkg -i /tmp/wazuh-agent_4.7.2-1_amd64.deb

    - name: Configurar o agente do Wazuh
      lineinfile:
        path: /var/ossec/etc/ossec.conf
        line: "<address>1.1.1.1</address>"
        insertbefore: "<port>1514</port>"
        state: present

    - name: Recarregar systemd
      shell: systemctl daemon-reload

    - name: Habilitar serviço do agente do Wazuh
      shell: systemctl enable wazuh-agent

    - name: Iniciar serviço do agente do Wazuh
      shell: systemctl start wazuh-agent
